### ISSUE TITLE
Outer circle color filling up the view that is showcased

### ISSUE THREAD

**Issue by joeytitans** [hamdiwanis/nativescript-app-tour#1]
Hello,

I'd first like to thank you for a wonderful plugin.  It's exactly what I've been looking for as I'm quickly approaching launch.

Anytime I showcase a button or view, the outer circle color is filling up the view.  I'm on android, and this is happening with both standard Buttons and the FAB Button plugin.

Here is the button that I want to view:
`<Button id="mapStyleButton" text="&#xf37b;" class="small-white-btn ionicon" ios:margin="15" tap="{{ openMapStyleDialog }}" />`

Here is the code to create the stop:
`
{
     view: this.page.getViewById("mapStyleButton"),
     title: "Customize the Map",
     description: "Options include maps for traffic, satellite maps, and more!",
     outerCircleColor: "#A52D5D",
     rippleColor: "black"
}
`

I've also attached the before and after screen in case I was ineffective at describing the issue.  Am I missing something on my part, or is this a known issue with the plugin?

Thank you!

![screen1](https://user-images.githubusercontent.com/37939256/41798755-7e4500ca-7634-11e8-8ea8-00086da14d0f.PNG)
![screen2](https://user-images.githubusercontent.com/37939256/41798757-80c98d20-7634-11e8-8ed9-7a0714e7a375.PNG)

**Comment by hamdiwanis** [comment]
hey, @joeytitans  thanks for both using the plugin and reporting the issue, it's fixed now and published to npm make sure to update, feel free to reopen the issue if you still facing it :)
