### ISSUE TITLE
I get an incompatibility error when I try to install it on iOS

### ISSUE THREAD

**Issue by ibnYusrat** [hamdiwanis/nativescript-app-tour#14]
Hi,

When I try to install the plugin for iOS I get this error:

![ios_error](https://user-images.githubusercontent.com/3955226/61519388-3880fc80-aa25-11e9-9984-fb08f1517d63.png)

Does it mean that my NativeScript version is too old for this plugin or the plugin is older for my NS version?

Please help.

Thank you.

**Comment by hamdiwanis** [comment]
this should not be an issue in the current version
