### ISSUE TITLE
Error when running tour - undefined is not an object - stop.view.ios

### ISSUE THREAD

**Issue by kianwilcox** [hamdiwanis/nativescript-app-tour#18]
I'm getting the following when clicking a button with startTour on it

NativeScript debugger attached.
CONSOLE ERROR file: node_modules/nativescript-vue/dist/index.js:2133:21: [Vue warn]: Error in v-on handler: "TypeError: undefined is not an object (evaluating 'stop.view.ios')"
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x10527960e NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x1052ba548 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x105cbb222 ffi_closure_unix64_inner
4   0x105cbbc4a ffi_closure_unix64
5   0x7fff485cbc83 -[UIControl sendAction:to:forEvent:]
6   0x7fff485cbfcb -[UIControl _sendActionsForEvents:withEvent:]
7   0x7fff485caf3c -[UIControl touchesEnded:withEvent:]
8   0x7fff48c55d10 -[UIWindow _sendTouchesForEvent:]
9   0x7fff48c57a95 -[UIWindow sendEvent:]
10  0x7fff48c31ed9 -[UIApplication sendEvent:]
11  0x7fff48cbc336 __dispatchPreprocessedEventFromEventQueue
12  0x7fff48cbf502 __handleEventQueueInternal
13  0x7fff48cb606b __handleHIDEventFetcherDrain
14  0x7fff23da1c71 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
15  0x7fff23da1b9c __CFRunLoopDoSource0
16  0x7fff23da1374 __CFRunLoopDoSources0
17  0x7fff23d9bf6e __CFRunLoopRun
18  0x7fff23d9b884 CFRunLoopRunSpecific
19  0x7fff38b5ac1a GSEventRunModal
20  0x7fff48c19220 UIApplicationMain
21  0x105cbba8d ffi_call_unix64
22  0x10babaf70
JavaScript stack trace:
file: node_modules/@proplugins/nativescript-app-tour/app-tour.ios.js:18:55
at map([native code])
at file: node_modules/@proplugins/nativescript-app-tour/app-tour.ios.js:16:36
at file: node_modules/@proplugins/nativescript-app-tour/app-tour.ios.js:46:29
at AppTour(file: node_modules/@proplugins/nativescript-app-tour/app-tour.common.js:33:8)
at AppTour(file: node_modules/@proplugins/nativescript-app-tour/app-tour.ios.js:8:52)
at startTour(file: app/components/App.vue:218:0)
at startTour([native code])
at invokeWithErrorHandling(file: node_modules/nativescript-vue/dist/index.js:3368:31)
at file: node_modules/@nativescript/core/data/observable/observable.js:110:31
at file: node_modules/@nativescript/core/data/observable/observable.js:127:24
at file: node_modules/@nativescript/core/ui/button/button.ios.js:216:24
at UIApplicationMain([native code])
at run(file: node_modules/@nativescript/core/application/application.ios.js:312:26)
at file: node_modules/nativescript-vue/dist/index.js:14069:2
at file:///app/bundle.js:1880:10
at ./main.js(file:///app/bundle.js:1884:34)
at __webpack_require__(file: app/webpack/bootstrap:750:0)
at checkDeferredModules(file: app/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: app/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
JavaScript error:
file: node_modules/@proplugins/nativescript-app-tour/app-tour.ios.js:18:55: JS ERROR TypeError: undefined is not an object (evaluating 'stop.view.ios')

my methods are below.

import { AppTour, TourStop, TourEvents } from "@proplugins/nativescript-app-tour";
... <Button ~feat1 .../> ... <Button ~feat2 .../>
methods: {
        startTour(){
            const stops = [
                {
                    view: this.$refs.feat1,
                    title: 'Feature 1',
                    description: "Feature 1 Description",
                    dismissable: true
                },
                {
                    view: this.$refs.feat2,
                    title: 'Feature 2',
                    description: 'Feature 2 Description',
                    outerCircleColor: 'orange',
                    rippleColor: 'black'
                }
            ];
        
            const handlers = {
                finish() {
                    console.log('Tour finished');
                },
                onStep(lastStopIndex) {
                    console.log('User stepped', lastStopIndex);
                },
                onCancel(lastStopIndex) {
                    console.log('User cancelled', lastStopIndex);
                }
            }
        
            this.tour = new AppTour(stops, handlers);
            this.tour.show();
        }
}
}...

**Comment by hamdiwanis** [comment]
hello, you are using a diffrent version mentained by proplugins ("@proplugins/nativescript-app-tour")

**Comment by dlcole** [comment]
Just FYI, this is the error message I see when I reference a view with an incorrect ID, such as with 

`view: page.getViewById("bogus-id"),`
