### ISSUE TITLE
Feature Request: support multi-page apps

### ISSUE THREAD

**Issue by dlcole** [hamdiwanis/nativescript-app-tour#19]
App-tour looks like a very useful plugin, and I'd like to use it for my app.  But, my app contains many pages, and I'd want the tour to explore more than just the home page.  It looks like what's needed is the ability to stop the current tour from within onStep, and then later start the tour again from a specified stop, effectively a pause/resume function. 

I'd be willing to contribute to this, 'tho my app is plain JavaScript.

**Comment by hamdiwanis** [comment]
why not just split the tour into smaller ones, run the first one then navigate to the next page then start the next tour and repeat

**Comment by dlcole** [comment]
That could make for lots of "mini-tours", but I'll investigate that.  

I'd also need [issue # 12](https://github.com/hamdiwanis/nativescript-app-tour/issues/12) addressed, as I have many side-drawer actions I'd want to highlight. 

Thanks for the quick reply!

**Comment by dlcole** [comment]
I've done enough investigation to conclude that multi-page apps can be supported by multiple, small tours that are chained together through the finish() event.  

I'll close this issue accordingly.
