### ISSUE TITLE
Tour is not working in ios 14.0

### ISSUE THREAD

**Issue by jitendraP-ashutec** [hamdiwanis/nativescript-app-tour#20]
I am using  below version.
```
nativescript Version: 7.0.10
iOS:14.0
Xcode: 12.0.1
```

Tour sequence is not working in ios. Tour open on first step but when click on first step, second step is not opening. Its doesn't show any error.

Thanks,
Jitendra Prajapati

**Comment by sido420** [comment]
any updates on this?

**Comment by ChadStrat** [comment]
+1 hoping someone has some insight on this one!

**Comment by PabloPG** [comment]
> I am using below version.
> 
> ```
> nativescript Version: 7.0.10
> iOS:14.0
> Xcode: 12.0.1
> ```
> 
> Tour sequence is not working in ios. Tour open on first step but when click on first step, second step is not opening. Its doesn't show any error.
> 
> Thanks,
> Jitendra Prajapati

got any solution?

**Comment by jitendraP-ashutec** [comment]
@ChadStrat  @PabloPG  I have added handlers in tours and its working on nativescript Version 7.0.10. You can also try this. My code

```
   const handlers: TourEvents = {
        finish() {
        },
        onStep(lastStopIndex) {
        },
        onCancel(lastStopIndex) {
        }
      }
      this.tour = new AppTour(stops);
      this.tour.buildNativeTour(stops, handlers);
      this.tour.show();

```

you could try, I think I should work for you also.

**Comment by PabloPG** [comment]
> @ChadStrat @PabloPG I have added handlers in tours and its working on nativescript Version 7.0.10. You can also try this. My code
> 
> ```
>    const handlers: TourEvents = {
>         finish() {
>         },
>         onStep(lastStopIndex) {
>         },
>         onCancel(lastStopIndex) {
>         }
>       }
>       this.tour = new AppTour(stops);
>       this.tour.buildNativeTour(stops, handlers);
>       this.tour.show();
> ```
> 
> you could try, I think I should work for you also.

Thanks for the quick response, but unfortunately it didn't work. I'm using ns 7.2

**Comment by ChadStrat** [comment]
This does not work for me either using 7.2.  here is how I am targeting:
```
    const stops: TourStop[] = [
        {
            view: this.page.getViewById("feat1"),
            dismissable: false,
            title: 'Title 1',
            description: "blah blah blah....",
        },
        {
            view: this.page.getViewById("feat2"),
            dismissable: false,
            title: 'Title 2',
            description: 'blah blah blah....',
        },
        {
          view: this.page.getViewById("feat3"),
          title: 'Title 3',
          description: 'blah blah blah....',
        }
    ];

    const handlers: TourEvents = {
      finish() {
          console.log('Tour finished');
      },
      onStep(lastStopIndex) {
          console.log('User stepped', lastStopIndex);
      },
      onCancel(lastStopIndex) {
          console.log('User cancelled', lastStopIndex);
      }
    }

    let tour = new AppTour(stops, handlers);
    tour.show();
```

onStep does not ever fire for me.

**Comment by ChadStrat** [comment]
this suggestion seems to have resolved the issue for me:  https://github.com/hamdiwanis/nativescript-app-tour/issues/16#issuecomment-588213863

adding tour.reset() prior to tour.show()

```
tour.reset();
```

**Comment by PabloPG** [comment]
> this suggestion seems to have resolved the issue for me: [#16 (comment)](https://github.com/hamdiwanis/nativescript-app-tour/issues/16#issuecomment-588213863)
> 
> adding tour.reset() prior to tour.show()
> 
> ```
> tour.reset();
> ```

I tried it too, but it didn't work.


Is this plugin in ProPlugins up to date? @hamdiwanis

**Comment by guillemc23** [comment]
I'd say the plugin here is not up-to-date, as it wasn't working for me either in Android with NS7 while it was working on NS6.

A cheap workaround I've found is to manually update the plugin dependencies inside `node_modules/nativescript-app-tour/app-tour.android.js` just by changing the imports from NS6 to NS7 like:

```
var color_1 = require("../@nativescript/core/color");
var application_1 = require("../@nativescript/core/application");
```

The sad part is that I have to redo it again each time I `ns clean`, but it doesn't happen too often since I'm a casual programmer. 

I haven't tested on iOS but Android is not working like a charm, and I have no reason to think it wouldn't do the trick in iOS too since I see old imports there too :-)

Maybe I should submit my changes for a new version? @hamdiwanis

**Comment by kriefsacha** [comment]
> @ChadStrat @PabloPG I have added handlers in tours and its working on nativescript Version 7.0.10. You can also try this. My code
> 
> ```
>    const handlers: TourEvents = {
>         finish() {
>         },
>         onStep(lastStopIndex) {
>         },
>         onCancel(lastStopIndex) {
>         }
>       }
>       this.tour = new AppTour(stops);
>       this.tour.buildNativeTour(stops, handlers);
>       this.tour.show();
> ```
> 
> you could try, I think I should work for you also.

this actually worked for me, i had an error on ios and with this it works. thanks !
