### ISSUE TITLE
Adding a step on the action bar

### ISSUE THREAD

**Issue by guillemc23** [hamdiwanis/nativescript-app-tour#21]
Well, so I have a tour set up and works nicely, but I can't set a TourStop pointing towards a button in the Action Bar. My button is a `NavigationButton` but it can't find it through its id. 

What is this different behavior? Is it possible to fix it?

Awesome plugin by the way @hamdiwanis <3

**Comment by hamdiwanis** [comment]
Thanks, I didn't have time to maintain this plugin for a while now, but as I remember this is an issue with the underling native library used here check this out https://github.com/hamdiwanis/nativescript-app-tour/issues/12
