### ISSUE TITLE
Feature Request: Can we have a skip tour button

### ISSUE THREAD

**Issue by DeepikaKochar** [hamdiwanis/nativescript-app-tour#4]
Hi Hamdiwanis,

Thanks for the great plugin. I have a request it would be good if we can have skip tour button rather than dismiss when clicked outside.

**Comment by hamdiwanis** [comment]
hey, @DeepikaKochar I think yes it could be but for now, the native libraries that this plugin is built upon does not provide this functionality, but the good news is there is already PRs for it so when they land I will be happy to update the plugin or maybe for them myself if I had time  :)

**Comment by hamdiwanis** [comment]
closed in favor of https://github.com/hamdiwanis/nativescript-app-tour/issues/5
