### ISSUE TITLE
Crash on IOS 12

### ISSUE THREAD

**Issue by standevo** [hamdiwanis/nativescript-app-tour#9]
Hi, I have a problem on IOS 12, it crashes. On Android works fine

**Comment by standevo** [comment]
Same issue also after releasing the new version.

**Comment by hamdiwanis** [comment]
sorry @shiv19 can you check this I think it's related to your PR

**Comment by shiv19** [comment]
@hamdiwanis this issue existed even before my PR

**Comment by shiv19** [comment]
@csi-stasik have you run `tns platform clean ios` after installing latest plugin?

**Comment by hamdiwanis** [comment]
@shiv19 i know it was I just mentioned you because I thought it was fixed by your PR :)

**Comment by standevo** [comment]
@shiv19, @hamdiwanis Hi, after some experiments I figured it out. I tried to call the apptour on the Switch component and it crashes. After I covered with StackLayout and it worked

```
<StackLayout id="feat1">
          <Switch
             id="feat2" <!-- If I use this it crashes --!>
            (loaded)="onSwitchLoaded($event)"
            (checkedChange)="onSwitchChange($event)"
            [checked]="value" 
           ></Switch> 
</StackLayout>
```
